### ISSUE TITLE
Prompt does not work for iOS

### ISSUE THREAD

**Issue by garfbargle** [AVGP/fake-terminal#1]
Hey Martin! I love what you built :) I forked and used your code as kind of like a [business card website](http://c0di.com). 

Anyways, I'm having trouble figuring out why I'm not able to type into the prompt on iOS. It works perfect on chrome on mac osx and android. Any ideas on where to start?

**Comment by AVGP** [comment]
Hey @garfbargle - thanks for your kind words and opening up this issue!
Cool website you're building there - so let's try to fix this issue, so you can finally show off!

Alright. I'm not having any iOS devices available, so I'll have to do some guessing, sorry for that in advance...
- Which iOS version are you running?
- Which browser on iOS have you tried?
- Can you do remote debugging and see, if there's any error displayed?
- When you say "I'm not able to type into the prompt" - do you mean there's just no input field (or no way to get an input cursor) available or is the text input itself somewhat problematic (but you get an editing cursor) or something else?

I will try to find somebody with an iPhone to test this with - but that can take a while...

**Comment by garfbargle** [comment]
Hey @AVGP , haha thank you. 
- ios 8.1.2 
- i've tried safari and chrome
- I'll look into remote debugging now
- I'm not able to even place a cursor or tap anywhere that would cause the keyboard to display. It's as if there is no input field.

**Comment by AVGP** [comment]
Hey, thanks for the lightning-fast answers!

The iOS version _may_ matter, as you're hitting the template polyfill as well, so one more potential source of the issue.

The fact that it behaves like there's no input field reminds me of something similar I've seen, I'll see if I can somehow reproduce!

We'll squash this bug together!

**Comment by garfbargle** [comment]
@AVGP I didn't think to try until now but this problem exists in safari on mac aswell, if you're using windows maybe you could try safari on there?

**Comment by garfbargle** [comment]
Here's one difference I'm seeing, the content tags are missing from safari 

# safari

![screen shot 2015-04-24 at 7 53 47 pm](https://cloud.githubusercontent.com/assets/1245620/7331187/b996ddf4-eabb-11e4-822f-8674f32f9b31.png)

# chrome

![screen shot 2015-04-24 at 7 53 28 pm](https://cloud.githubusercontent.com/assets/1245620/7331189/bc975862-eabb-11e4-8033-4c0a5a9c6ba5.png)

**Comment by AVGP** [comment]
That's because Safari is using the Polyfill.

There's two things that may be happening:

1.) The z-index order is wrong in Safari, meaning that the "contenteditable" span (`class="input"`) is covered up by the promt span or
2.) Safari does not support `contenteditable="true"` (seems implausible, given http://caniuse.com/#feat=contenteditable)

**Comment by garfbargle** [comment]
Okay, I'm quite noob when it comes to web. Does that mean you think it can be solved with css?

**Comment by AVGP** [comment]
Perhaps, yes...

Try editing terminal.css like this:

``` css
fake-terminal::shadow #terminal .input {
    height:         1em;
    min-width:      1em;
    outline-color:  transparent;
    border:         none;
    display:        inline-block;
}
```

and add this line

``` css
z-index: 10;
```

like this:

``` css
fake-terminal::shadow #terminal .input {
    height:         1em;
    min-width:      1em;
    outline-color:  transparent;
    border:         none;
    display:        inline-block;
    z-index: 10;
}
```
